# Generated by Django 2.2 on 2020-07-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(choices=[(0, 'Normal'), (5, 'Member'), (9, 'Admin')], default=0),
        ),
    ]
