# Generated by Django 2.2 on 2020-07-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='benefits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='travel_stipend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='agma',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='housing',
            field=models.BooleanField(default=False),
        ),
    ]
