# Generated by Django 2.2 on 2020-07-18 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20200714_1630'),
        ('vocalist_app', '0002_auto_20200714_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_reported', to='user_app.User')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_reports', to='vocalist_app.Review')),
            ],
        ),
    ]
