# Generated by Django 2.2 on 2020-07-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalist_app', '0003_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='YAPRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weekly_stipend', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('category', models.CharField(max_length=20)),
                ('agma', models.BooleanField(default=False)),
                ('housing', models.BooleanField(default=False)),
                ('travel_stipend', models.BooleanField(default=False)),
                ('benefits', models.BooleanField(default=False)),
                ('minimum_age', models.IntegerField(blank=True, null=True)),
                ('maximum_age', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
