# Generated by Django 2.2 on 2020-07-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalist_app', '0004_yaprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yaprequest',
            name='weekly_stipend',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
