# Generated by Django 2.2 on 2020-07-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalist_app', '0005_auto_20200719_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yaprequest',
            name='maximum_age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='yaprequest',
            name='minimum_age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
